(function () {
    'use strict';

    angular.module('i2sFinance.resources', [
        'i2sFinance.resources.valideUnicite',
        'i2sFinance.resources.usager',
        'i2sFinance.resources.viInfoUsager',
        'i2sFinance.resources.viInfoBase',
        'i2sFinance.resources.axeVisibiliteUsagerResource',
        'i2sFinance.resources.actionSystemeResource',
        'i2sFinance.resources.viAnalyseRegleSommaireInfoPoste',
        'i2sFinance.resources.solde',
        'i2sFinance.resources.sousPosteBudgetaire',
        'i2sFinance.resources.sousPosteBudgetaireRegle',
        'i2sFinance.resources.viAnalyseRegleDetailInfo',
        'i2sFinance.resources.viRegleSousPosteBudgetaire',
        'i2sFinance.resources.viAnalyseRegleCompteFluxPeriode',
        'i2sFinance.resources.regle',
        'i2sFinance.resources.regleImpact',
        'i2sFinance.resources.regleDate',
        'i2sFinance.resources.regleException',
        'i2sFinance.resources.regleExceptionVentilation',
        'i2sFinance.resources.viRegleTransfertCompte',
        'i2sFinance.resources.viRegleSolde',
        'i2sFinance.resources.viSousPosteBudgetaire',
        'i2sFinance.resources.viPosteBudgetaire',
        'i2sFinance.resources.viSousPosteBudgetaireRegleValidation',
        'i2sFinance.resources.viRegleAjustement',
        'i2sFinance.resources.viRegleException',
        'i2sFinance.resources.viRegleExceptionCache',
        'i2sFinance.resources.viAnalyseRegleDetail',
        'i2sFinance.resources.importFileResource',
        'i2sFinance.resources.viConciliationSectionDepRev',
        'i2sFinance.resources.viRapportDetailleSectionCompteCredit',
        'i2sFinance.resources.viRapportDetailleSectionDepRev',
        'i2sFinance.resources.viRapport',
        'i2sFinance.resources.viRapportSommaireSectionDepRev',
        'i2sFinance.resources.budgetResource',
        'i2sFinance.resources.viReglePosteBudgetaire',
        'i2sFinance.resources.posteBudgetaire',
        'i2sFinance.resources.profil',
        'i2sFinance.resources.viSequenceMax',
        'i2sFinance.resources.banque',
        'i2sFinance.resources.banqueCompte',
        'i2sFinance.resources.viLienBancaire',
        'i2sFinance.resources.plaidResource'
    ]);

})();
